const bloodGroups = ['O+', 'O-', 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-'];

const lastNames = [
  'Harry',
  'Ross',
  'Bruce',
  'Cook',
  'Carolyn',
  'Morgan',
  'Albert',
  'Walker',
  'Randy',
  'Reed',
  'Larry',
  'Barnes',
  'Lois',
  'Wilson',
  'Jesse',
  'Campbell',
  'Ernest',
  'Rogers',
  'Theresa',
  'Patterson',
  'Henry',
  'Simmons',
  'Michelle',
  'Perry',
  'Frank',
  'Butler',
  'Shirley',
];

const firstNames = [
  'Ruth',
  'Jackson',
  'Debra',
  'Allen',
  'Gerald',
  'Harris',
  'Raymond',
  'Carter',
  'Jacqueline',
  'Torres',
  'Joseph',
  'Nelson',
  'Carlos',
  'Sanchez',
  'Ralph',
  'Clark',
  'Jean',
  'Alexander',
  'Stephen',
  'Roberts',
  'Eric',
  'Long',
  'Amanda',
  'Scott',
  'Teresa',
  'Diaz',
  'Wanda',
  'Thomas',
];

const astroSpecializations = [
  'Pilot',
  'Marksman',
  'Engineer',
  'Medic',
  'Infiltrator',
  'Heavy_Weapons_Specialist',
  'Tech_Hacker',
  'Demolition_Expert',
  'Scout',
  'Sniper',
  'CQC_Specialist',
  'Shield_Operator',
  'Communications_Specialist',
  'Strategist',
  'Stealth_Operative',
  'Mechanic',
  'Astrobiologist',
  'Navigator',
  'Psychic_Operative',
  'Drones_Specialist',
];

const trooperCodenames = {
  Pilot: [
    'Starstriker',
    'CosmicRaptor',
    'NebulaNavigator',
    'QuantumPhoenix',
    'VelocityVortex',
    'AstroAce',
    'StellarWingman',
    'EclipseEagle',
    'CelestialSkydancer',
    'InfinityIcarus',
    'LunarLancer',
    'GalacticGlider',
    'SolarSprinter',
    'NovaNavigator',
    'AstralAviator',
    'StardustSurfer',
    'QuasarQuester',
    'AstroFalcon',
    'NighthawkNebula',
    'StratosphereStrider',
  ],
  Marksman: [
    'ShadowSharpshooter',
    'LongshotLegend',
    'PrecisionPhantom',
    'SnipeSpecter',
    'BullseyeBanshee',
    'GhostGunslinger',
    'ViperVisionary',
    'EagleEyeEliminator',
    'SilentSniper',
    'SwiftShooter',
    'PhantomPrecision',
    'LunarLethal',
    'StarSightStriker',
    'CosmicCrackshot',
    'BlitzBullseye',
    'SolarSharpshooter',
    'AstroAssassin',
    'StellarSniper',
    'QuantumQuickshot',
    'CelestialCrusader',
  ],
  Engineer: [
    'QuantumQuartermaster',
    'TechTrailblazer',
    'MechMender',
    'CircuitCraftsman',
    'GadgetGenius',
    'AstroArtisan',
    'NebulaNurturer',
    'InventorInstigator',
    'RobotRover',
    'StarshipSmith',
    'GalacticGreaseMonkey',
    'CosmicConstructor',
    'InfinityInnovator',
    'QuantumQuasar',
    'SolarSculptor',
    'StellarSystemSculptor',
    'NuclearNanotechnician',
    'CelestialCrafter',
    'AstroArchitect',
    'NebulaNomad',
  ],
  Medic: [
    'HealingHarbinger',
    'LunarLifebringer',
    'CelestialCaretaker',
    'NebulaNurse',
    'QuantumQuackDoctor',
    'AstralAngel',
    'StellarSurgeon',
    'SolarSavior',
    'StarlightSamaritan',
    'CosmicCurer',
    'GalacticGuardian',
    'InfinityInoculator',
    'AeroApothecary',
    'AstroAlleviator',
    'NebulaNurturer',
    'EtherealEmissary',
    'QuantumQuickHealer',
    'StarSootheSorcerer',
    'CrisisCrafter',
    'AstroAngel',
  ],
  Infiltrator: [
    'StealthShadow',
    'SilentSpecter',
    'GhostlyInfiltrator',
    'PhantomProwler',
    'LunarLurker',
    'NightshadeNinja',
    'StarlightStalker',
    'EclipseEscapist',
    'QuantumQuicksilver',
    'ShadowSerpent',
    'AstroAssassin',
    'NebulaNinja',
    'CosmicCovert',
    'InvisibleInfiltrator',
    'CelestialChameleon',
    'NebulaNinja',
    'GhostGuerilla',
    'StellarSaboteur',
    'QuantumQuickshifter',
    'AstralAgent',
  ],
  Heavy_Weapons_Specialist: [
    'QuantumQuake',
    'AstroAnnihilator',
    'StellarStorm',
    'CosmicCannon',
    'NovaNuke',
    'BlackHoleBlaster',
    'QuantumQuasar',
    'StarstrikeSledge',
    'LunarLaser',
    'EclipticExterminator',
    'AstroAvalanche',
    'SolarSmasher',
    'NebulaNemesis',
    'CelestialCyclone',
    'SupernovaSlugger',
    'QuantumQuiver',
    'StellarShockwave',
    'InfinityInferno',
    'GalacticGatling',
    'CosmicCrusher',
  ],
  Tech_Hacker: [
    'QuantumQuerent',
    'CodeCrusader',
    'DigitalDynamo',
    'BitBountyHunter',
    'ByteBuccaneer',
    'NeuralNinja',
    'CryptoCommander',
    'FirewallFalcon',
    'QuantumQuickHack',
    'VirusVoyager',
    'CyberCrafter',
    'DataDart',
    'BinaryBuccaneer',
    'InfoInfiltrator',
    'TechTrailblazer',
    'CircuitSaboteur',
    'SiliconSorcerer',
    'NebulaNavigator',
    'QuantumQuasar',
    'CosmicCrusader',
  ],
  Demolition_Expert: [
    'BoomBuccaneer',
    'DetonatorDynamo',
    'BlastBlazer',
    'ExplosiveEnigma',
    'PyroPhantom',
    'QuantumQuake',
    'DemolitionDervish',
    'BlastwaveBanshee',
    'MegaMarauder',
    'NovaNapalm',
    'DoomsdayDart',
    'C4Cyclone',
    'QuantumQuasar',
    'CosmicCrusader',
    'BlackHoleBomber',
    'QuantumQuickQuake',
    'EclipticExplosioneer',
    'AstroAvalanche',
    'SolarSmasher',
    'GalacticGatling',
  ],
  Scout: [
    'ShadowScout',
    'LunarLookout',
    'CelestialSurveyor',
    'NebulaNavigator',
    'QuantumQuickQuest',
    'AstroApparition',
    'StellarSurveyor',
    'EclipseExplorer',
    'InvisibleInvestigator',
    'QuantumQuester',
    'AstroAgent',
    'NebulaNomad',
    'CosmicCartographer',
    'GalacticGuide',
    'InfinityInventor',
    'SolarSeeker',
    'StellarStrider',
    'NebulaNomad',
    'EclipticExplorer',
    'QuantumQuickQuasar',
  ],
  Sniper: [
    'ShadowSharpshooter',
    'LongshotLegend',
    'PrecisionPhantom',
    'SnipeSpecter',
    'BullseyeBanshee',
    'GhostGunslinger',
    'ViperVisionary',
    'EagleEyeEliminator',
    'SilentSniper',
    'SwiftShooter',
    'PhantomPrecision',
    'LunarLethal',
    'StarSightStriker',
    'CosmicCrackshot',
    'BlitzBullseye',
    'SolarSharpshooter',
    'AstroAssassin',
    'StellarSniper',
    'QuantumQuickshot',
    'CelestialCrusader',
  ],
  CQC_Specialist: [
    'ShadowStriker',
    'LunarLion',
    'CelestialCheetah',
    'NebulaNinja',
    'QuantumQuickQuake',
    'AstroAvalanche',
    'StellarStriker',
    'EclipseEliminator',
    'QuantumQuicksilver',
    'ShadowSerpent',
    'AstroAssassin',
    'NebulaNinja',
    'CosmicCrackshot',
    'InvisibleInfiltrator',
    'CelestialChameleon',
    'NebulaNinja',
    'GhostGuerilla',
    'StellarSaboteur',
    'QuantumQuickshifter',
    'AstralAgent',
  ],
  Shield_Operator: [
    'GuardianGlacier',
    'QuantumQuasar',
    'AstroAegis',
    'StellarShielder',
    'CelestialCenturion',
    'NebulaNebula',
    'EclipticEnforcer',
    'CosmicBulwark',
    'SolarSafeguard',
    'QuantumQuickGuard',
    'AeroAegis',
    'LunarLifeguard',
    'AstroArmorer',
    'NebulaNurturer',
    'CelestialChampion',
    'EtherealEmissary',
    'QuantumQuickBarricade',
    'StarSafekeeper',
    'StellarSentry',
    'InfinityInferno',
  ],
  Communications_Specialist: [
    'QuantumQuerent',
    'SignalSorcerer',
    'CelestialCipher',
    'AstroAmbassador',
    'StellarSender',
    'NebulaNomad',
    'CosmicCourier',
    'QuantumQuickComms',
    'EclipticEmissary',
    'SpaceSignalSorcerer',
    'GalacticGhost',
    'SolarSilencer',
    'LunarListener',
    'AstroAmplifier',
    'NebulaNavigator',
    'CelestialChanneler',
    'InfinityInterlocutor',
    'QuantumQuasar',
    'CosmicCrusader',
    'AstroArchitect',
  ],
  Strategist: [
    'QuantumQuester',
    'CosmicCrafter',
    'StellarStrategist',
    'AstroAdvisor',
    'CelestialCommander',
    'NebulaNomad',
    'GalacticGeneral',
    'SolarSchemer',
    'QuantumQuickQuest',
    'AeroArchitect',
    'InfinityInsight',
    'LunarLuminary',
    'AstroArchitect',
    'EclipticEnvisioner',
    'CosmicConductor',
    'StellarSchemer',
    'NebulaNavigator',
    'CelestialChampion',
    'EtherealEmissary',
    'QuantumQuasar',
  ],
  Stealth_Operative: [
    'ShadowSilencer',
    'LunarLurker',
    'NebulaNinja',
    'QuantumQuickQuicksilver',
    'AstroAssassin',
    'EclipticEmissary',
    'StellarStalker',
    'CelestialChameleon',
    'NebulaNinja',
    'GhostGuerilla',
    'InvisibleInfiltrator',
    'QuantumQuickshifter',
    'AstralAgent',
    'QuantumQuicksilver',
    'AstroAssassin',
    'NebulaNinja',
    'CosmicCovert',
    'GhostlyGuerilla',
    'ShadowSerpent',
    'NebulaNomad',
  ],
  Mechanic: [
    'QuantumQuartermaster',
    'TechTrailblazer',
    'MechMender',
    'CircuitCraftsman',
    'GadgetGenius',
    'AstroArtisan',
    'NebulaNurturer',
    'InventorInstigator',
    'RobotRover',
    'StarshipSmith',
    'GalacticGreaseMonkey',
    'CosmicConstructor',
    'InfinityInnovator',
    'QuantumQuasar',
    'SolarSculptor',
    'StellarSystemSculptor',
    'NuclearNanotechnician',
    'CelestialCrafter',
    'AstroArchitect',
    'NebulaNomad',
  ],
  Astrobiologist: [
    'QuantumQuester',
    'CosmicCrafter',
    'StellarStrategist',
    'AstroAdvisor',
    'CelestialCommander',
    'NebulaNomad',
    'GalacticGeneral',
    'SolarSchemer',
    'QuantumQuickQuest',
    'AeroArchitect',
    'InfinityInsight',
    'LunarLuminary',
    'AstroArchitect',
    'EclipticEnvisioner',
    'CosmicConductor',
    'StellarSchemer',
    'NebulaNavigator',
    'CelestialChampion',
    'EtherealEmissary',
    'QuantumQuasar',
  ],
  Navigator: [
    'QuantumQuester',
    'CosmicCrafter',
    'StellarStrategist',
    'AstroAdvisor',
    'CelestialCommander',
    'NebulaNomad',
    'GalacticGeneral',
    'SolarSchemer',
    'QuantumQuickQuest',
    'AeroArchitect',
    'InfinityInsight',
    'LunarLuminary',
    'AstroArchitect',
    'EclipticEnvisioner',
    'CosmicConductor',
    'StellarSchemer',
    'NebulaNavigator',
    'CelestialChampion',
    'EtherealEmissary',
    'QuantumQuasar',
  ],
  Psychic_Operative: [
    'QuantumQuerent',
    'MindMarauder',
    'CosmicCognitor',
    'AstralAugur',
    'EtherealEnchantor',
    'QuantumQuickQuasar',
    'CelestialClairvoyant',
    'StarSoothsayer',
    'LunarLuminator',
    'NebulaNavigator',
    'AstroAugury',
    'GalacticGhost',
    'InfinityIntuition',
    'SolarSeer',
    'StellarSorcerer',
    'EclipticEnigma',
    'CosmicConjurer',
    'NebulaNebula',
    'QuantumQuasar',
    'AstroArchitect',
  ],

  Drones_Specialist: [
    'GalacticGlider',
    'QuantumQuadPilot',
    'AstroAviator',
    'NebulaNavigator',
    'CosmicCopter',
    'StellarSkySurfer',
    'EclipticExplorer',
    'InfinityInterceptor',
    'SolarScout',
    'QuantumQuickQuadrone',
    'CelestialCruiser',
    'AstroAeroAce',
    'LunarLift',
    'NebulaNimbus',
    'EtherealExpeditionist',
    'StarStratospheric',
    'CosmicCirrus',
    'NebulaNebula',
    'QuantumQuasar',
  ],
};

const astroGear = {
  Pilot: [
    ['AstroFlight Suit - Starlight (A-22)', 'AstroFlight Suit - Nebula (A-23)'],
    ['Quantum Thruster Pack - Blaze (B-44)', 'Quantum Thruster Pack - Aurora (B-45)'],
    ['Photon Shielding Helmet - Celestial (H-11)', 'Photon Shielding Helmet - Galactic (H-12)'],
    ['Gravity Deflector Boots - Stellar (G-33)', 'Gravity Deflector Boots - Lunar (G-34)'],
  ],

  Marksman: [
    ['Energy Absorption Vest - Hawkeye (V-17)', 'Energy Absorption Vest - Eagle (V-18)'],
    ['Hawk-Eye Visor - Precision (H-13)', 'Hawk-Eye Visor - Sharpshooter (H-14)'],
    ['Jump Boots - Skyward (J-27)', 'Jump Boots - Gravity (J-28)'],
    ['Stealth Camouflage Cloak - Shadow (S-31)', 'Stealth Camouflage Cloak - Phantom (S-32)'],
  ],

  Engineer: [
    ['Anti-Gravity Boots - Levitate (A-35)', 'Anti-Gravity Boots - Soar (A-36)'],
    ['Plasma Welding Helmet - Spark (P-51)', 'Plasma Welding Helmet - Forge (P-52)'],
    ['Repair Nanobots Suit - Fixer (R-21)', 'Repair Nanobots Suit - Builder (R-22)'],
    ['Tech Exo-Skeleton - Mechanic (T-41)', 'Tech Exo-Skeleton - Innovator (T-42)'],
  ],

  Medic: [
    [
      'Biohazard Protection Gloves - Guardian (B-53)',
      'Biohazard Protection Gloves - Sentinel (B-54)',
    ],
    ['Medical Drone Harness - Rescuer (M-37)', 'Medical Drone Harness - Savior (M-38)'],
    ['Nano-Healing Suit - Vitality (N-61)', 'Nano-Healing Suit - Lifesaver (N-62)'],
    ['Regenerative Shield - Revitalizer (R-23)', 'Regenerative Shield - Renewer (R-24)'],
  ],

  Infiltrator: [
    [
      'Holographic Disguise Module - Mirage (H-31)',
      'Holographic Disguise Module - Illusion (H-32)',
    ],
    ['Phase Shifter Wristbands - Shroud (P-61)', 'Phase Shifter Wristbands - Veil (P-62)'],
    ['Shadow Cloak - Phantom (S-41)', 'Shadow Cloak - Ghost (S-42)'],
    ['Silent Steps Boots - Whisper (S-27)', 'Silent Steps Boots - Stealth (S-28)'],
  ],

  Heavy_Weapons_Specialist: [
    ['Energy Shield Gauntlets - Sentinel (E-21)', 'Energy Shield Gauntlets - Guardian (E-22)'],
    ['Power Armor - Titan (P-71)', 'Power Armor - Colossus (P-72)'],
    ['Rocket Propulsion Boots - Meteor (R-31)', 'Rocket Propulsion Boots - Comet (R-32)'],
    ['Titanium Battle Helmet - Behemoth (T-81)', 'Titanium Battle Helmet - Leviathan (T-82)'],
  ],

  Tech_Hacker: [
    ['Neural Interface Suit - Quantum (N-41)', 'Neural Interface Suit - Cipher (N-42)'],
    ['Digital Camouflage Boots - Stealth (D-31)', 'Digital Camouflage Boots - Phantom (D-32)'],
    ['Cybernetic Helmet - Network (C-51)', 'Cybernetic Helmet - Firewall (C-52)'],
    ['Encryption Gauntlets - Sentinel (E-33)', 'Encryption Gauntlets - Guardian (E-34)'],
  ],

  Demolition_Expert: [
    ['Blast-Proof Suit - Demolisher (B-61)', 'Blast-Proof Suit - Annihilator (B-62)'],
    ['Heavy-Duty Blast Boots - Impact (H-71)', 'Heavy-Duty Blast Boots - Shockwave (H-72)'],
    ['Demolition Helmet - Destructor (D-41)', 'Demolition Helmet - Obliterator (D-42)'],
    ['Reinforced Gauntlets - Demolition (R-41)', 'Reinforced Gauntlets - Devastator (R-42)'],
  ],

  Scout: [
    ['Camouflage Suit - Shadow (C-61)', 'Camouflage Suit - Phantom (C-62)'],
    ['Stealth Boots - Whisper (S-61)', 'Stealth Boots - Silence (S-62)'],
    ['Recon Helmet - Eagle Eye (R-51)', 'Recon Helmet - Hawk Vision (R-52)'],
    ['Camouflage Gloves - Ghost (C-63)', 'Camouflage Gloves - Specter (C-64)'],
  ],

  Sniper: [
    ['Sniper Ghillie Suit - Shadow (S-51)', 'Sniper Ghillie Suit - Phantom (S-52)'],
    ['Longshot Boots - Whisper (L-31)', 'Longshot Boots - Silence (L-32)'],
    ['Scope Helmet - Eagle Eye (H-21)', 'Scope Helmet - Hawk Vision (H-22)'],
    ['Precision Gloves - Ghost (P-41)', 'Precision Gloves - Specter (P-42)'],
  ],

  CQC_Specialist: [
    ['CQC Combat Suit - Shadow (C-71)', 'CQC Combat Suit - Phantom (C-72)'],
    ['Agile Boots - Sprint (A-41)', 'Agile Boots - Dash (A-42)'],
    ['Close Quarters Helmet - Fury (H-31)', 'Close Quarters Helmet - Rampage (H-32)'],
    ['Combat Gloves - Frenzy (C-73)', 'Combat Gloves - Havoc (C-74)'],
  ],

  Shield_Operator: [
    ['Shielded Exo-Suit - Guardian (S-51)', 'Shielded Exo-Suit - Sentinel (S-52)'],
    ['Sturdy Boots - Defender (B-31)', 'Sturdy Boots - Protector (B-32)'],
    ['Shielded Helmet - Aegis (H-21)', 'Shielded Helmet - Bulwark (H-22)'],
    ['Reinforced Gauntlets - Warden (R-41)', 'Reinforced Gauntlets - Defender (R-42)'],
  ],

  Communications_Specialist: [
    ['Communications Suit - Transmitter (C-61)', 'Communications Suit - Receiver (C-62)'],
    ['Wireless Boots - Signal (B-31)', 'Wireless Boots - Connection (B-32)'],
    ['Headset Helmet - Broadcast (H-51)', 'Headset Helmet - Receptor (H-52)'],
    ['Transmission Gloves - Sender (T-21)', 'Transmission Gloves - Receiver (T-22)'],
  ],

  Strategist: [
    ['Tactical Suit - Mastermind (T-61)', 'Tactical Suit - Planner (T-62)'],
    ['Strategic Boots - Insight (S-41)', 'Strategic Boots - Intellect (S-42)'],
    ['Command Helmet - Authority (H-31)', 'Command Helmet - Wisdom (H-32)'],
    ['Strategic Gloves - Judgement (S-61)', 'Strategic Gloves - Decision (S-62)'],
  ],

  Stealth_Operative: [
    ['Stealth Suit - Shadow (S-61)', 'Stealth Suit - Phantom (S-62)'],
    ['Silent Boots - Whisper (S-41)', 'Silent Boots - Hush (S-42)'],
    ['Cloak Helmet - Conceal (H-31)', 'Cloak Helmet - Disguise (H-32)'],
    ['Invisible Gloves - Veil (I-21)', 'Invisible Gloves - Camouflage (I-22)'],
  ],

  Mechanic: [
    ['Mechanic Jumpsuit - Techmaster (M-61)', 'Mechanic Jumpsuit - Innovator (M-62)'],
    ['Heavy Boots - Sturdy (H-41)', 'Heavy Boots - Durable (H-42)'],
    ['Mechanic Helmet - Engineer (H-51)', 'Mechanic Helmet - Builder (H-52)'],
    ['Grease-Stained Gloves - Precision (G-31)', 'Grease-Stained Gloves - Dexterity (G-32)'],
  ],

  Astrobiologist: [
    ['Astrobiology Suit - Explorer (A-61)', 'Astrobiology Suit - Discoverer (A-62)'],
    ['Explorer Boots - Trek (E-41)', 'Explorer Boots - Journey (E-42)'],
    ['Researcher Helmet - Knowledge (R-31)', 'Researcher Helmet - Wisdom (R-32)'],
    ['Analytical Gloves - Analyze (A-41)', 'Analytical Gloves - Synthesize (A-42)'],
  ],

  Navigator: [
    ['Navigator Uniform - Guide (N-61)', 'Navigator Uniform - Pathfinder (N-62)'],
    ['Traveler Boots - Expedition (T-41)', 'Traveler Boots - Trek (T-42)'],
    ['Navigator Helmet - Direction (H-51)', 'Navigator Helmet - Chart (H-52)'],
    ['Explorer Gloves - Expedition (E-31)', 'Explorer Gloves - Discovery (E-32)'],
  ],

  Psychic_Operative: [
    ['Psionic Suit - Mindbender (P-61)', 'Psionic Suit - Telepath (P-62)'],
    ['Mind Boots - Psychic (M-41)', 'Mind Boots - Visionary (M-42)'],
    ['Telepathic Helmet - Insight (H-51)', 'Telepathic Helmet - Vision (H-52)'],
    ['Psy-Gloves - Illusionist (P-41)', 'Psy-Gloves - Clairvoyant (P-42)'],
  ],

  Drones_Specialist: [
    ['Drone Operator Suit - Commander (D-61)', 'Drone Operator Suit - Operator (D-62)'],
    ['Commander Boots - Authority (B-41)', 'Commander Boots - Control (B-42)'],
    ['Drone Operator Helmet - Vision (H-51)', 'Drone Operator Helmet - Control (H-52)'],
    ['Control Gloves - Precision (C-31)', 'Control Gloves - Override (C-32)'],
  ],
};

const planetNames = [
  'Astrion-1025',
  'Stellara-3487',
  'Celestia-6912',
  'Orbiton-5734',
  'Galaxium-8190',
  'Nebula-2468',
  'Quasar-1357',
  'Solaris-9802',
  'Cosmara-6048',
  'Lunara-7531',
  'AstroNova-2184',
  'Starlight-7659',
  'SkySphere-4096',
  'Infinity-5721',
  'Eclipse-8943',
  'Cynosure-6310',
  'Vortex-1853',
  'Supernova-9276',
  'Pulsar-5031',
  'Cosmosis-3498',
  'Voyager-6214',
  'Spectra-7845',
  'Nebulon-3690',
  'Exoplanet-8142',
  'AstroQuotient-4502',
  'GalacticCore-1076',
  'Aurora-2983',
  'Stellaris-5860',
  'Nebulous-7264',
  'Celestial-8901',
  'Quantum-1342',
  'NovaPrime-6750',
  'Zenith-5039',
  'StarQuest-2198',
  'Orion-3675',
  'Utopia-5824',
  'Aether-4906',
  'Elysium-8601',
  'Vivid-3129',
  'Nexara-7063',
  'Luminary-1548',
  'Polaris-4682',
  'Vesta-8135',
  'Aegis-2457',
  'Serenity-6290',
  'AstroSphere-7582',
  'Pandora-9234',
  'Horizon-2846',
];

const planetSizes = [
  'Terrestrial',
  'Super-Earth',
  'Sub-Neptune',
  'Neptune-like',
  'Gas Dwarf',
  'Gas Giant',
  'Ice Giant',
  'Mini-Neptune',
  'Sub-Saturn',
  'Saturn-like',
  'Jovian',
  'Sub-Jovian',
  'Micro-Jovian',
  'Mega-Earth',
  'Dwarf Planet',
  'Moonlet',
  'Exomoon',
  'Mega-Jupiter',
  'Mini-Mercury',
  'Mini-Mars',
  'Mega-Mercury',
  'Mega-Mars',
  'Sub-Uranus',
  'Uranus-like',
  'Sub-Pluto',
  'Pluto-like',
  'Exoplanet',
  'Proto-Planet',
  'Protoplanetesimal',
  'Gas-Dominated',
  'Ice-Dominated',
  'Rocky',
  'Chthonian',
  'Iron Planet',
  'Ocean Planet',
  'Silicate Planet',
  'Carbon Planet',
  'Helium Planet',
  'Sub-Brown Dwarf',
  'Brown Dwarf',
  'Failed Star',
  'Hot Jupiter',
  'Hot Neptune',
  'Warm Jupiter',
  'Warm Neptune',
  'Cold Jupiter',
  'Cold Neptune',
];

const climateValues = [
  'Tropical',
  'Subtropical',
  'Desert',
  'Arid',
  'Temperate',
  'Continental',
  'Polar',
  'Alpine',
  'Mediterranean',
  'Oceanic',
  'Equatorial',
  'Savanna',
  'Tundra',
  'Boreal',
  'Monsoon',
  'Ice Cap',
  'Highland',
  'Steppe',
  'Rainforest',
  'Taiga',
  'Subarctic',
  'Humid Subtropical',
  'Semi-Arid',
  'Humid Continental',
  'Polar Desert',
  'Subpolar Oceanic',
  'Ice Shelf',
  'Hot Desert',
  'Cold Desert',
  'Alpine Tundra',
  'Tropical Rainforest',
  'Temperate Rainforest',
  'Boreal Forest',
  'Montane',
  'Lowland',
  'Highland Desert',
  'Lowland Rainforest',
  'Lowland Forest',
  'Montane Rainforest',
  'Montane Forest',
  'Tropical Savanna',
  'Temperate Savannah',
  'Polar Ice Cap',
  'Lowland Tundra',
  'Highland Tundra',
  'Arctic Tundra',
  'Mountainous',
];

const resourceValues = [
  'Ore',
  'Minerals',
  'Crystals',
  'Metals',
  'Gems',
  'Exotic Elements',
  'Rare Earth Elements',
  'Fuel Cells',
  'Biofuel',
  'Energy Crystals',
  'Hydrocarbons',
  'Organic Compounds',
  'Silicate Deposits',
  'Water Ice',
  'Helium-3',
  'Carbon Nanotubes',
  'Nanomaterials',
  'Plasma Residue',
  'Quantum Particles',
  'Anti-Matter',
  'Dark Matter',
  'Plasma Crystals',
  'Enriched Uranium',
  'Titanium Alloy',
  'Lithium Deposits',
  'Geothermal Energy',
  'Biological Samples',
  'Synthetic Polymers',
  'Advanced Alloys',
  'Exoplanetary Soil',
  'Ionic Crystals',
  'Fusion Cores',
  'Rare Gases',
  'Magnetic Resonance Materials',
  'Xenon Isotopes',
  'Hydrogen Extracts',
  'Geodes',
  'Biomimetic Materials',
  'Volcanic Ash',
  'Quantum Computing Elements',
  'Gamma-Ray Emitters',
  'Radiant Crystals',
  'Hyperium',
  'Nanobots',
  'Genetic Sequences',
  'Quantum Entanglement Nodes',
];

function pickRand(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function planetGen() {
  return {
    name: pickRand(planetNames),
    size: Math.floor(Math.random() * (10000 - 1000) + 1000),
    climate: pickRand(climateValues),
    resources: [pickRand(resourceValues), pickRand(resourceValues), pickRand(resourceValues)],
  };
}

export function recruitGen() {
  const statGen = () => {
    return Math.floor(Math.random() * (100 - 40) + 40);
  };

  return {
    firstName: firstNames[Math.floor(Math.random() * firstNames.length)],
    lastName: lastNames[Math.floor(Math.random() * lastNames.length)],
    age: Math.floor(Math.random() * (70 - 20) + 20),
    bloodGroup: bloodGroups[Math.floor(Math.random() * bloodGroups.length)],
    stats: {
      health: statGen(),
      agility: statGen(),
      strength: statGen(),
      intelligence: statGen(),
      luck: statGen(),
    },
  };
}

export function trainRecruits(recruitsArr) {
  const battleReadyAstros = recruitsArr.map((rec) => {
    const spec = astroSpecializations[Math.floor(Math.random() * astroSpecializations.length)];
    const specBasedCodeName =
      trooperCodenames[spec][Math.floor(Math.random() * trooperCodenames[spec].length)];

    return {
      ...rec,
      spec: spec,
      codeName: specBasedCodeName,
      rank: 0,
    };
  });
  return battleReadyAstros;
}

export function astroAutoEquip(astroArr) {
  const equippedAstros = astroArr.map((astro) => ({
    ...astro,
    equipment: {
      bodyArmor: astroGear[astro.spec][0][Math.floor(Math.random())],
      footWear: astroGear[astro.spec][1][Math.floor(Math.random())],
      headGear: astroGear[astro.spec][2][Math.floor(Math.random())],
      hands: astroGear[astro.spec][3][Math.floor(Math.random())],
    },
  }));
  return equippedAstros;
}
